apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    name: my-deployment
spec:
  selector:
    matchLabels:
      app: my-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: my-deployment
          image: azarel9/prj_image:${J_VERSION}
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: my-deployment
  labels:
    app: my-deployment
spec:
  type: NodePort
  ports:
    - name: port
      port: 8000
      targetPort: 8080
  selector:
    app: my-deployment